# Generated by Django 5.0.1 on 2024-03-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
