# Generated by Django 5.0.1 on 2024-03-05 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rating_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='article.article'),
        ),
    ]
